
const {
	GraphQLID,
  GraphQLNonNull,
  GraphQLString,
} = require("graphql");

const answerTypeGql = {
  id: { type: GraphQLID },
  email: { type: GraphQLNonNull(GraphQLString) },
  demo_genre: { type: GraphQLString }, 
  demo_age: { type: GraphQLString }, 
  demo_titre: { type: GraphQLString }, 
  demo_fonctions: { type: GraphQLString }, 
  demo_administration: { type: GraphQLString }, 
  demo_status: { type: GraphQLString }, 
  demo_rythme: { type: GraphQLString }, 
  travail_activite: { type: GraphQLString }, 
  travail_activite_autre: { type: GraphQLString }, 
  demo_entree_admin: { type: GraphQLString }, 
  demo_etudiant: { type: GraphQLString }, 
  education_formation: { type: GraphQLString }, 
  demo_plus_hautes_etudes: { type: GraphQLString }, 
  education_formation: { type: GraphQLString }, 
  recherches_info: { type: GraphQLString }, 
  panel1: { type: GraphQLString }, 
  premiere_ligne_code: { type: GraphQLString }, 
  experience_programmation: { type: GraphQLString }, 
  programmation_pro: { type: GraphQLString }, 
  language_pas_expert: { type: GraphQLString }, 
  language_expert: { type: GraphQLString }, 
  frameworks_web: { type: GraphQLString }, 
  autres_libs: { type: GraphQLString }, 
  connaissance_db: { type: GraphQLString }, 
  connaissance_db_expert: { type: GraphQLString }, 
  plateformes_os: { type: GraphQLString }, 
  containers_bool: { type: GraphQLString }, 
  panel2: { type: GraphQLString }, 
  os_principal: { type: GraphQLString }, 
  editeur_principal: { type: GraphQLString }, 
  travail_bureau_domicile: { type: GraphQLString }, 
  taille_structure: { type: GraphQLString }, 
  profils_tech: { type: GraphQLString }, 
  satisfaction: { type: GraphQLString }, 
  recherche_travail: { type: GraphQLString }, 
  recherche_travail_secteur: { type: GraphQLString }, 
}; 

 module.exports = answerTypeGql;